service: moixa-demo

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    dontPrintOutput: true

functions:
  hello:
    handler: main.handler
    events:
      - http:
          integration: lambda-proxy
          path: /consumption
          method: GET
